language: go

go:
  - "1.10.x"
  - master

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2

script:
  - golangci-lint run
  - go test -v -race ./...