name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.12
        uses: actions/setup-go@v2
        with:
          go-version: 1.12
      - name: Run tests
        run: go test -v ./...
